name: "ubuntu | python 3.9 | 3.10 | 3.11 "

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          # - "3.11"
    name: Ubuntu Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          pip install -r requirements.txt
          pip install pytest
          python -m pytest tests/test_inference_server.py 
